USE [RussiaNews]
GO



CREATE TABLE [dbo].[AbramsonTerm](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](500) NOT NULL,
	[Collect] [bit] NOT NULL DEFAULT 1,
 CONSTRAINT [PK_AbramsonTerm] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [U_AbramsonTerm_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO AbramsonTerm (Name) VALUES ('ACU Strategic Partners')
INSERT INTO AbramsonTerm (Name) VALUES ('Adamant')
INSERT INTO AbramsonTerm (Name) VALUES ('Affliction Entertainment')
INSERT INTO AbramsonTerm (Name) VALUES ('Aras Agalarov') 

INSERT INTO AbramsonTerm (Name) VALUES ('Emin Agalarov') 
INSERT INTO AbramsonTerm (Name) VALUES ('Rinat Akhmetshin') 
INSERT INTO AbramsonTerm (Name) VALUES ('Alfa Bank')
INSERT INTO AbramsonTerm (Name) VALUES ('Alfa Capital Partners')
INSERT INTO AbramsonTerm (Name) VALUES ('Yulya Alferova') 
INSERT INTO AbramsonTerm (Name) VALUES ('Kamil Ekim Alptekin') 
INSERT INTO AbramsonTerm (Name) VALUES ('Apollo Global Management')
INSERT INTO AbramsonTerm (Name) VALUES ('Tevfik Arif') 
INSERT INTO AbramsonTerm (Name) VALUES ('Trajche Arsov') 
INSERT INTO AbramsonTerm (Name) VALUES ('Andrey Artemenko') 
INSERT INTO AbramsonTerm (Name) VALUES ('Association of Accredited Public Policy Advocates to the European Union')
INSERT INTO AbramsonTerm (Name) VALUES ('Association of Former Intelligence Officers')
INSERT INTO AbramsonTerm (Name) VALUES ('Pyotr Aven') 
INSERT INTO AbramsonTerm (Name) VALUES ('Robert Baer') 
INSERT INTO AbramsonTerm (Name) VALUES ('Arron Banks') 
INSERT INTO AbramsonTerm (Name) VALUES ('Andrey Baranov') 
INSERT INTO AbramsonTerm (Name) VALUES ('Thomas Barrack') 
INSERT INTO AbramsonTerm (Name) VALUES ('Kerrie Baylis')
INSERT INTO AbramsonTerm (Name) VALUES ('Bayrock Group')
INSERT INTO AbramsonTerm (Name) VALUES ('Shera Bechard')
INSERT INTO AbramsonTerm (Name) VALUES ('Stanislav Belkovsky')
INSERT INTO AbramsonTerm (Name) VALUES ('Leon Black')
INSERT INTO AbramsonTerm (Name) VALUES ('Black Cube')
INSERT INTO AbramsonTerm (Name) VALUES ('Anna Bogacheva')
INSERT INTO AbramsonTerm (Name) VALUES ('Elliott Broidy')
INSERT INTO AbramsonTerm (Name) VALUES ('Brookfield Asset Management')
INSERT INTO AbramsonTerm (Name) VALUES ('Pete Brownell')
INSERT INTO AbramsonTerm (Name) VALUES ('Mark Burnett')
INSERT INTO AbramsonTerm (Name) VALUES ('Richard Burt')
INSERT INTO AbramsonTerm (Name) VALUES ('Maria Butina')
INSERT INTO AbramsonTerm (Name) VALUES ('CAATSA') 
INSERT INTO AbramsonTerm (Name) VALUES ('Countering America''s Adversaries Through Sanctions Act')
INSERT INTO AbramsonTerm (Name) VALUES ('Cambridge Analytica')
INSERT INTO AbramsonTerm (Name) VALUES ('L. Jean Camp')
INSERT INTO AbramsonTerm (Name) VALUES ('Michael Caputo') 
INSERT INTO AbramsonTerm (Name) VALUES ('Center for Security Policy')
INSERT INTO AbramsonTerm (Name) VALUES ('Center for the National Interest')
INSERT INTO AbramsonTerm (Name) VALUES ('Yuri Chaika')
INSERT INTO AbramsonTerm (Name) VALUES ('Sam Clovis')
INSERT INTO AbramsonTerm (Name) VALUES ('Alex Copson')
INSERT INTO AbramsonTerm (Name) VALUES ('Mark Corallo')
INSERT INTO AbramsonTerm (Name) VALUES ('Carrie Cordero')
INSERT INTO AbramsonTerm (Name) VALUES ('Randy Credico')
INSERT INTO AbramsonTerm (Name) VALUES ('Crocus Group')
INSERT INTO AbramsonTerm (Name) VALUES ('Seth Cropsey') 
INSERT INTO AbramsonTerm (Name) VALUES ('Olivia Culpo')
INSERT INTO AbramsonTerm (Name) VALUES ('Yossi Dagan')
INSERT INTO AbramsonTerm (Name) VALUES ('Tera Dahl') 
INSERT INTO AbramsonTerm (Name) VALUES ('Daily Dot')
INSERT INTO AbramsonTerm (Name) VALUES ('DCLeaks')
INSERT INTO AbramsonTerm (Name) VALUES ('Rick Dearborn')
INSERT INTO AbramsonTerm (Name) VALUES ('Diana Denman')
INSERT INTO AbramsonTerm (Name) VALUES ('David Dennison')
INSERT INTO AbramsonTerm (Name) VALUES ('Oleg Deripaska') 
INSERT INTO AbramsonTerm (Name) VALUES ('Kirill Dmitriev')
INSERT INTO AbramsonTerm (Name) VALUES ('James Dodson') 
INSERT INTO AbramsonTerm (Name) VALUES ('Oliver Dollimore') 
INSERT INTO AbramsonTerm (Name) VALUES ('Dosug')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexander Downer')
INSERT INTO AbramsonTerm (Name) VALUES ('Yuri Dubinin')
INSERT INTO AbramsonTerm (Name) VALUES ('Arkady Dvorkovich')
INSERT INTO AbramsonTerm (Name) VALUES ('Fedor Emelianenko')
INSERT INTO AbramsonTerm (Name) VALUES ('Boris Epshteyn')
INSERT INTO AbramsonTerm (Name) VALUES ('Jeffrey Epstein')
INSERT INTO AbramsonTerm (Name) VALUES ('Paul Erickson')
INSERT INTO AbramsonTerm (Name) VALUES ('Oleg Erovinkin')
INSERT INTO AbramsonTerm (Name) VALUES ('Essential Consultants')
INSERT INTO AbramsonTerm (Name) VALUES ('eTurboNews')
INSERT INTO AbramsonTerm (Name) VALUES ('European Council on Foreign Relations')
INSERT INTO AbramsonTerm (Name) VALUES ('FBIAnon')
INSERT INTO AbramsonTerm (Name) VALUES ('Oxana Fedorova')
INSERT INTO AbramsonTerm (Name) VALUES ('Flynn Intelligence Group')
INSERT INTO AbramsonTerm (Name) VALUES ('Matthew Freedman')
INSERT INTO AbramsonTerm (Name) VALUES ('FreedomFest')
INSERT INTO AbramsonTerm (Name) VALUES ('Mikhail Fridman')
INSERT INTO AbramsonTerm (Name) VALUES ('Frontier Services Group')
INSERT INTO AbramsonTerm (Name) VALUES ('Alan Futerfas')
INSERT INTO AbramsonTerm (Name) VALUES ('Alan Garten')
INSERT INTO AbramsonTerm (Name) VALUES ('Rick Gates')
INSERT INTO AbramsonTerm (Name) VALUES ('Glencore')
INSERT INTO AbramsonTerm (Name) VALUES ('Global Partners in Diplomacy')
INSERT INTO AbramsonTerm (Name) VALUES ('Rob Goldstone')
INSERT INTO AbramsonTerm (Name) VALUES ('Vladimir Golubev') 
INSERT INTO AbramsonTerm (Name) VALUES ('Sergei Gordeev') 
INSERT INTO AbramsonTerm (Name) VALUES ('J. D. Gordon') 
INSERT INTO AbramsonTerm (Name) VALUES ('Sergei Gorkov')
INSERT INTO AbramsonTerm (Name) VALUES ('Nikolair Gorokhov')
INSERT INTO AbramsonTerm (Name) VALUES ('Rhona Graff')
INSERT INTO AbramsonTerm (Name) VALUES ('Herman Gref')
INSERT INTO AbramsonTerm (Name) VALUES ('Christo Grozev')
INSERT INTO AbramsonTerm (Name) VALUES ('Haaretz')
INSERT INTO AbramsonTerm (Name) VALUES ('Douglas Hagmann')
INSERT INTO AbramsonTerm (Name) VALUES ('Steven Hall')
INSERT INTO AbramsonTerm (Name) VALUES ('Stefan Halper')
INSERT INTO AbramsonTerm (Name) VALUES ('Hungarian Free Press')
INSERT INTO AbramsonTerm (Name) VALUES ('Sean Illing') 
INSERT INTO AbramsonTerm (Name) VALUES ('Internet Research Agency')
INSERT INTO AbramsonTerm (Name) VALUES ('Julia Ioffe') 
INSERT INTO AbramsonTerm (Name) VALUES ('IP3 International')
INSERT INTO AbramsonTerm (Name) VALUES ('James Kadtke')
INSERT INTO AbramsonTerm (Name) VALUES ('Brittany Kaiser')
INSERT INTO AbramsonTerm (Name) VALUES ('Marianna Kakaounaki')
INSERT INTO AbramsonTerm (Name) VALUES ('Panos Kammenos') 
INSERT INTO AbramsonTerm (Name) VALUES ('Kostas Karamanlis')
INSERT INTO AbramsonTerm (Name) VALUES ('George Kaveladze')
INSERT INTO AbramsonTerm (Name) VALUES ('Ike Kaveladze')
INSERT INTO AbramsonTerm (Name) VALUES ('David Keene')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexander Khomenko')
INSERT INTO AbramsonTerm (Name) VALUES ('Vassilis Kikilias')
INSERT INTO AbramsonTerm (Name) VALUES ('Konstantin Kilimnik') 
INSERT INTO AbramsonTerm (Name) VALUES ('Kirsanova Realty')
INSERT INTO AbramsonTerm (Name) VALUES ('Sergey Kislyak') 
INSERT INTO AbramsonTerm (Name) VALUES ('Artem Klyushin') 
INSERT INTO AbramsonTerm (Name) VALUES ('Aleksandr Kogan') 
INSERT INTO AbramsonTerm (Name) VALUES ('Nikos Kotzias') 
INSERT INTO AbramsonTerm (Name) VALUES ('Vladimir Kozhin') 
INSERT INTO AbramsonTerm (Name) VALUES ('Sergei Krivov') 
INSERT INTO AbramsonTerm (Name) VALUES ('Charles Kubic') 
INSERT INTO AbramsonTerm (Name) VALUES ('Charles Kushner')
INSERT INTO AbramsonTerm (Name) VALUES ('Natalia Kutepova-Jamrom')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexei Kuzmichev') 
INSERT INTO AbramsonTerm (Name) VALUES ('Chuck LaBella')
INSERT INTO AbramsonTerm (Name) VALUES ('Yigal Landau')
INSERT INTO AbramsonTerm (Name) VALUES ('Bryan Lanza')
INSERT INTO AbramsonTerm (Name) VALUES ('Lars Larson')
INSERT INTO AbramsonTerm (Name) VALUES ('David Laufman')
INSERT INTO AbramsonTerm (Name) VALUES ('Jared Leto')
INSERT INTO AbramsonTerm (Name) VALUES ('Lev Leviev')
INSERT INTO AbramsonTerm (Name) VALUES ('Joshua Levy')
INSERT INTO AbramsonTerm (Name) VALUES ('Liberty Writers News')
INSERT INTO AbramsonTerm (Name) VALUES ('LifeZette')
INSERT INTO AbramsonTerm (Name) VALUES ('Svetlana Lokhova')
INSERT INTO AbramsonTerm (Name) VALUES ('London Center of International Law Practice')
INSERT INTO AbramsonTerm (Name) VALUES ('Howard Lorber')
INSERT INTO AbramsonTerm (Name) VALUES ('Abbe Lowell')
INSERT INTO AbramsonTerm (Name) VALUES ('Yuri Luzhkov')
INSERT INTO AbramsonTerm (Name) VALUES ('Martha MacCallum')
INSERT INTO AbramsonTerm (Name) VALUES ('Alicia Machado')
INSERT INTO AbramsonTerm (Name) VALUES ('Sergei Magnitsky')
INSERT INTO AbramsonTerm (Name) VALUES ('Magnitsky Act')
INSERT INTO AbramsonTerm (Name) VALUES ('Make America Number 1 PAC')
INSERT INTO AbramsonTerm (Name) VALUES ('Andrey Malanin')
INSERT INTO AbramsonTerm (Name) VALUES ('Ted Malloch')
INSERT INTO AbramsonTerm (Name) VALUES ('Mandiner')
INSERT INTO AbramsonTerm (Name) VALUES ('Simona Mangiante')
INSERT INTO AbramsonTerm (Name) VALUES ('John Mashburn')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexander Mashkevitch')
INSERT INTO AbramsonTerm (Name) VALUES ('Petros Mavroidis')
INSERT INTO AbramsonTerm (Name) VALUES ('Mary McCord')
INSERT INTO AbramsonTerm (Name) VALUES ('Dmitry Medvedev')
INSERT INTO AbramsonTerm (Name) VALUES ('Joseph Mifsud') 
INSERT INTO AbramsonTerm (Name) VALUES ('Andranik Migranyan')
INSERT INTO AbramsonTerm (Name) VALUES ('Sergei Millian')
INSERT INTO AbramsonTerm (Name) VALUES ('Mirax Group')
INSERT INTO AbramsonTerm (Name) VALUES ('Kyriakos Mitsotakis')
INSERT INTO AbramsonTerm (Name) VALUES ('Bert Mizusawa') 
INSERT INTO AbramsonTerm (Name) VALUES ('Semion Mogilevich')
INSERT INTO AbramsonTerm (Name) VALUES ('Moscow Millionaire Fair')
INSERT INTO AbramsonTerm (Name) VALUES ('Randy Moss')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexander Murinson')
INSERT INTO AbramsonTerm (Name) VALUES ('George Nader')
INSERT INTO AbramsonTerm (Name) VALUES ('National Security Advisory Committee')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexei Navalny') 
INSERT INTO AbramsonTerm (Name) VALUES ('Boris Nemtsov')
INSERT INTO AbramsonTerm (Name) VALUES ('New Economic School')
INSERT INTO AbramsonTerm (Name) VALUES ('Victoria Nuland') 
INSERT INTO AbramsonTerm (Name) VALUES ('Sam Nunberg') 
INSERT INTO AbramsonTerm (Name) VALUES ('Bruce Ohr')
INSERT INTO AbramsonTerm (Name) VALUES ('Operation Crossfire Hurricane')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexis Papachelas')
INSERT INTO AbramsonTerm (Name) VALUES ('George Papadopoulos')
INSERT INTO AbramsonTerm (Name) VALUES ('Brad Parscale')
INSERT INTO AbramsonTerm (Name) VALUES ('Justine Pasek')
INSERT INTO AbramsonTerm (Name) VALUES ('W. Samuel Patten')
INSERT INTO AbramsonTerm (Name) VALUES ('Prokopis Pavlopoulos')
INSERT INTO AbramsonTerm (Name) VALUES ('David Pecker')
INSERT INTO AbramsonTerm (Name) VALUES ('Dmitry Peskov')
INSERT INTO AbramsonTerm (Name) VALUES ('Sergey Petrushin')
INSERT INTO AbramsonTerm (Name) VALUES ('Charles Phalen')
INSERT INTO AbramsonTerm (Name) VALUES ('Walid Phares') 
INSERT INTO AbramsonTerm (Name) VALUES ('Pobeda oil field')
INSERT INTO AbramsonTerm (Name) VALUES ('Olga Polonskaya') 
INSERT INTO AbramsonTerm (Name) VALUES ('Petro Poroshenko')
INSERT INTO AbramsonTerm (Name) VALUES ('Alicia Powe') 
INSERT INTO AbramsonTerm (Name) VALUES ('Bill Priestap')
INSERT INTO AbramsonTerm (Name) VALUES ('Sergey Eduardovich Prikhodko') 
INSERT INTO AbramsonTerm (Name) VALUES ('Erik Prince')
INSERT INTO AbramsonTerm (Name) VALUES ('PropOrNot')
INSERT INTO AbramsonTerm (Name) VALUES ('Project Zulu')
INSERT INTO AbramsonTerm (Name) VALUES ('Psy Group')
INSERT INTO AbramsonTerm (Name) VALUES ('Matt Purdy')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexey Pushkov')
INSERT INTO AbramsonTerm (Name) VALUES ('atar Investment Authority') 
INSERT INTO AbramsonTerm (Name) VALUES ('Ratio Oil Exploration')
INSERT INTO AbramsonTerm (Name) VALUES ('Ritz-Carlton Moscow')
INSERT INTO AbramsonTerm (Name) VALUES ('Dmitry Rogozin')
INSERT INTO AbramsonTerm (Name) VALUES ('Dana Rohrabacher') 
INSERT INTO AbramsonTerm (Name) VALUES ('Alexander Romanov')
INSERT INTO AbramsonTerm (Name) VALUES ('Rotem Rosen')
INSERT INTO AbramsonTerm (Name) VALUES ('Rosneft')
INSERT INTO AbramsonTerm (Name) VALUES ('Rostec')
INSERT INTO AbramsonTerm (Name) VALUES ('Andrei Rozov') 
INSERT INTO AbramsonTerm (Name) VALUES ('Giorgi Rtskhiladze')
INSERT INTO AbramsonTerm (Name) VALUES ('Phil Ruffin')
INSERT INTO AbramsonTerm (Name) VALUES ('Russian Direct Investment Fund')
INSERT INTO AbramsonTerm (Name) VALUES ('Russian Institute for Strategic Studies')
INSERT INTO AbramsonTerm (Name) VALUES ('Russian International Affairs Council')
INSERT INTO AbramsonTerm (Name) VALUES ('Sergei Ryabkov')
INSERT INTO AbramsonTerm (Name) VALUES ('James Rybicki')
INSERT INTO AbramsonTerm (Name) VALUES ('Nastya Rybka') 
INSERT INTO AbramsonTerm (Name) VALUES ('Dmitry Rybolovlev')
INSERT INTO AbramsonTerm (Name) VALUES ('Konstantin Rykov') 
INSERT INTO AbramsonTerm (Name) VALUES ('Jonathan Safron')
INSERT INTO AbramsonTerm (Name) VALUES ('St. Petersburg International Economic Forum')
INSERT INTO AbramsonTerm (Name) VALUES ('William Saletan') 
INSERT INTO AbramsonTerm (Name) VALUES ('Alex Sapir')
INSERT INTO AbramsonTerm (Name) VALUES ('Tamir Sapir')
INSERT INTO AbramsonTerm (Name) VALUES ('Sapir Organization')
INSERT INTO AbramsonTerm (Name) VALUES ('Kata Sarka')
INSERT INTO AbramsonTerm (Name) VALUES ('Felix Sater') 
INSERT INTO AbramsonTerm (Name) VALUES ('Sberbank')
INSERT INTO AbramsonTerm (Name) VALUES ('Jeremy Scahill')
INSERT INTO AbramsonTerm (Name) VALUES ('Dan Scavino')
INSERT INTO AbramsonTerm (Name) VALUES ('Schengen Area')
INSERT INTO AbramsonTerm (Name) VALUES ('Joseph Schmitz') 
INSERT INTO AbramsonTerm (Name) VALUES ('SCL Group')
INSERT INTO AbramsonTerm (Name) VALUES ('Darrell Scott')
INSERT INTO AbramsonTerm (Name) VALUES ('Igor Sechin') 
INSERT INTO AbramsonTerm (Name) VALUES ('Allen Shapiro')
INSERT INTO AbramsonTerm (Name) VALUES ('Alex Shnaider')
INSERT INTO AbramsonTerm (Name) VALUES ('Paula Shugart')
INSERT INTO AbramsonTerm (Name) VALUES ('Konstantin Sidorkov')
INSERT INTO AbramsonTerm (Name) VALUES ('Dimitri Simes')
INSERT INTO AbramsonTerm (Name) VALUES ('Glenn Simpson')
INSERT INTO AbramsonTerm (Name) VALUES ('Andrei Soldatov')
INSERT INTO AbramsonTerm (Name) VALUES ('Sotheby''s International Realty')
INSERT INTO AbramsonTerm (Name) VALUES ('Dimitriy Streshinskiy')
INSERT INTO AbramsonTerm (Name) VALUES ('SVR')
INSERT INTO AbramsonTerm (Name) VALUES ('Matt Tait')
INSERT INTO AbramsonTerm (Name) VALUES ('Ivan Timofeev') 
INSERT INTO AbramsonTerm (Name) VALUES ('Victoria Toensing') 
INSERT INTO AbramsonTerm (Name) VALUES ('Alimzhan Tokhtakhounov')
INSERT INTO AbramsonTerm (Name) VALUES ('Alexander Torshin') 
INSERT INTO AbramsonTerm (Name) VALUES ('Daniel Treisman') 
INSERT INTO AbramsonTerm (Name) VALUES ('True Pundit')
INSERT INTO AbramsonTerm (Name) VALUES ('George Tzitzikos')
INSERT INTO AbramsonTerm (Name) VALUES ('Craig Unger') 
INSERT INTO AbramsonTerm (Name) VALUES ('Valdai Discussion Club') 
INSERT INTO AbramsonTerm (Name) VALUES ('Alex Van der Zwaan')
INSERT INTO AbramsonTerm (Name) VALUES ('Bob Van Ronkel')
INSERT INTO AbramsonTerm (Name) VALUES ('Maureen Van Zandt')
INSERT INTO AbramsonTerm (Name) VALUES ('Viktor Vekselberg')
INSERT INTO AbramsonTerm (Name) VALUES ('Guy Verhofstadt')
INSERT INTO AbramsonTerm (Name) VALUES ('Natalia Veselnitskaya') 
INSERT INTO AbramsonTerm (Name) VALUES ('Vnesheconombank')
INSERT INTO AbramsonTerm (Name) VALUES ('VR Systems')
INSERT INTO AbramsonTerm (Name) VALUES ('VTB')
INSERT INTO AbramsonTerm (Name) VALUES ('Alex Wade') 
INSERT INTO AbramsonTerm (Name) VALUES ('Paris Wade') 
INSERT INTO AbramsonTerm (Name) VALUES ('Clint Watts') 
INSERT INTO AbramsonTerm (Name) VALUES ('Allen Weisselberg') 
INSERT INTO AbramsonTerm (Name) VALUES ('Wikistrat')
INSERT INTO AbramsonTerm (Name) VALUES ('Suttipong Wongpin')
INSERT INTO AbramsonTerm (Name) VALUES ('Paul Wood')
INSERT INTO AbramsonTerm (Name) VALUES ('Samuel Woolley')  
INSERT INTO AbramsonTerm (Name) VALUES ('WorldNetDaily') 
INSERT INTO AbramsonTerm (Name) VALUES ('Vladimir Yakunin') 
INSERT INTO AbramsonTerm (Name) VALUES ('Viktor Yanukovych') 
INSERT INTO AbramsonTerm (Name) VALUES ('Joel Zamel') 
INSERT INTO AbramsonTerm (Name) VALUES ('Zembla')

SELECT b.Term, Count(*)
FROM MediaCloudBatch b
JOIN MediaCloudStory s ON s.MediaCloudBatchID = b.ID 
JOIN AbramsonTerm a ON a.Name = b.Term
WHERE b.ID > 30 AND a.Collect = 1 
GROUP BY b.Term ORDER By Count(*) DESC



UPDATE AbramsonTerm SET Collect = 0 WHERE Name = 'Adamant'
UPDATE AbramsonTerm SET Collect = 0 WHERE Name = 'Mark Burnett'
UPDATE AbramsonTerm SET Collect = 0 WHERE Name = 'Haaretz'
UPDATE AbramsonTerm SET Collect = 0 WHERE Name = 'Haaretz'
UPDATE AbramsonTerm SET Collect = 0 WHERE Name = 'Alicia Machado'
UPDATE AbramsonTerm SET Collect = 0 WHERE Name = 'Randy Moss'
